apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-node
spec:
  serviceName: data-service
  replicas: 2
  selector:
    matchLabels:
      app: es-data
  template:
    metadata:
      labels:
        app: es-data
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: "elastic-search"
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "master-node-0.es-service"
          - name: cluster.initial_master_nodes
            value: "master-node-0"
          - name: ES_JAVA_OPTS      
            value: "-Xms512m -Xmx512m"
          - name: node.roles  
            value: data
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
     
  volumeClaimTemplates:
  - metadata:
      name: esclastic-data
      labels:
        app: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: essc
      resources:
        requests:
          storage: 500Mi
---
kind: Service
apiVersion: v1
metadata:
  name: data-service

  labels:
    app: es-data
spec:
  selector:
    app: es-data
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node         